### ISSUE TITLE
INT pin of the MCP2515

### ISSUE THREAD

**Issue by AlexandreBras** [autowp/arduino-mcp2515#16]
Hello.

I can not find any reference in the libraries to the INT pin from the MCP2515. Can I assume that the INT pin is not necessary to connect ?

Thank you.

**Comment by autowp** [comment]
You can find an example of INT usage here https://github.com/autowp/arduino-canhacker/blob/master/examples/usb_cdc/usb_cdc/usb_cdc.ino
