### ISSUE TITLE
How does the library handle error messages?

### ISSUE THREAD

**Issue by azoz158** [autowp/arduino-mcp2515#17]
Hey guys. The library has been working amazing so far. I just couldn't find a reference in the code or documentation that tells how would the code handle error frames that comes from CAN. Could you direct me to a resource and specific cod in the library that handles these errors?

Cheers

**Comment by autowp** [comment]
You can identify ERR message by the flag in ID 
https://github.com/autowp/arduino-mcp2515/blob/master/can.h#L20
