### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by grcasanova** [autowp/arduino-mcp2515#2]
Could you include a wiring setup including SPI connections? Thanks

**Comment by autowp** [comment]
I think wiring is trivial
[http://ota.net.br/wp-content/uploads/2017/04/mb_canbus_schema.png](http://ota.net.br/wp-content/uploads/2017/04/mb_canbus_schema.png)

**Comment by fragmuffin** [comment]
Trivial: yes
Obvious: no :wink:

**Comment by trysten** [comment]
@autowp I think this issue can be closed. More illustrations would be nice, but the existing ones seems sufficient.
