### ISSUE TITLE
Reading standard and extended packages at the same time

### ISSUE THREAD

**Issue by exp1ore** [autowp/arduino-mcp2515#23]
Hello. How to read standard and extended packages at the same time?

**Comment by autowp** [comment]
Don't know about any limitations. Did you tried and got error?

**Comment by jxltom** [comment]
You could disable filtering by setting ```RXBnCTRL_RXM_STDEXT``` to ```0x11```

**Comment by jxltom** [comment]
I think this is fixed by https://github.com/autowp/arduino-mcp2515/pull/35
