### ISSUE TITLE
How to define a Extended Frame Format ?

### ISSUE THREAD

**Issue by HaganHao** [autowp/arduino-mcp2515#3]
I have try to send a message within Extended Frame Format.
When I use a USB-CAN Analyst to read the message, it show me wrong ID, And I was told it is Stranded Frame Format.

**Comment by autowp** [comment]
Add [CAN_EFF_FLAG](https://github.com/autowp/arduino-mcp2515/blob/master/can.h#L13) to message id

```
struct can_frame canMsg;

canMsg.can_id  = 0x0F6 | CAN_EFF_FLAG;
canMsg.can_dlc = 1;
canMsg.data[0] = 0x8E;
```

**Comment by HaganHao** [comment]
Thank you very much. works good.

**Comment by autowp** [comment]
Welcome

**Comment by sebasira** [comment]
Hi! Thanks for your work I appreciate that. This issue was very useful to me because the README is worng, it says **CAN_EFF_MASK;** instead of **CAN_EFF_FLAG*. And it was not working until I use the corerct name.

Please correct for future users!

**Comment by autowp** [comment]
@sebasira thanks, fixed

**Comment by ShrishgovindTork** [comment]
@autowp what can I do to receive Extended CAN Frame??
