### ISSUE TITLE
Use different pins on Adafruit Metro M0?

### ISSUE THREAD

**Issue by wma12** [autowp/arduino-mcp2515#42]
Hi,

I want to learn a bit more about CAN-Bus and therefore use an Adafruit Metro M0 to receive some can-messages. On all the wiring diagrams and instructions I find, the MCP2515 module is connected to D2 and D10-13. However D2-D10 are already used on my Adafruit Metro M0 Express. Only D0(RX), D1(TX), A4, A5 and D11-13 are still free. Can I also use these pins instead? And how to change it? In the initialization I only see a way to set the CSI pin:

MCP2515 mcp2515(10);

What about the other pins? How do I change them?

**Comment by autowp** [comment]
Arduino SPI pins is defined in board specific files of original library https://www.arduino.cc/en/reference/SPI

That question is out of scope of mcp2515 library.

We can configure only ChipSelect
