### ISSUE TITLE
Multiple Nodes, 1 Receiver, 2 Transmitter

### ISSUE THREAD

**Issue by Al9900** [autowp/arduino-mcp2515#49]
Hello, i need to communicate with 3 arduinos, 2 transmitter data and one receiver.. But how can i coordinate them? im wondering what can happen when both trasnmitter put on the can line different data with different ID. Maybe they coordinate by theyself and keep the data message in the buffer? Or i need to write a function for this? Thanks a lot

**Comment by autowp** [comment]
CAN protocol solved that. There is id-based priorities and retries on hardware level

**Comment by Al9900** [comment]
Need i to setup something more in the firmware ? How did it decides the priorities?

**Comment by autowp** [comment]
https://en.wikipedia.org/wiki/CAN_bus
Ctrl+F "Priority"
