### ISSUE TITLE
faulty function can_id

### ISSUE THREAD

**Issue by Betacarotin** [autowp/arduino-mcp2515#52]
Hi! 
I am sending a CAN message with id 0x11 (17 dec, 10001 bin) and reading the received CAN id with this command:
`  Serial.print("Message read: ");
    Serial.print(canMsg.can_id);
    Serial.print(" = ");
    Serial.println(CAN_receive);`

The output is:
`Message read: 2147483665 = 17`
 
which is 80000011 in hex, or a 32bit binary. So it is making an output of 32bits on a 29 bit identifier. Maybe it is returning some other parts of the identifier/frame? 

Or do I use this function wrong?

**Comment by autowp** [comment]
EFF/RTR/ERR flags
https://github.com/autowp/arduino-mcp2515/blob/master/can.h
