### ISSUE TITLE
Checking Free Buffer

### ISSUE THREAD

**Issue by KamikaceDixit** [autowp/arduino-mcp2515#9]
Hello! Thanks a lot for this project, it is incredible. I'm having a problem when I try to send a lot of messages one after the other. I only receive a few of them. If i use a delay between messages, the problem is solved, but I wanted to know if there is a function to check if the buffer is free to send the next one instead the delay.
I hope you can help me. Thank you a lot!

**Comment by autowp** [comment]
Check sendMessage implementation. You find loop over TX registers looking for empty

**Comment by KamikaceDixit** [comment]
Thank you a lot, I didn't noticed about the return of sendMessage, I can use that.
Thank you and congratulations for your work!
